name: Build packages

on: [push]

env:
  DOCKERHUB_USER: tvoneicken
  DOCKER_IMAGE: sensorgnome-dockcross

permissions:
  id-token: write
  contents: write

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          # login use access token: https://docs.docker.com/docker-hub/access-tokens/
          username: ${{ env.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKER_IMAGE }}
          flavor: |
            latest=true
            prefix=armv7-rpi-bullseye-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
